name: Run Python Script

on:
  push

jobs:
  run-script:
    name: Run Python Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run Script
        run: python main.py
        env:
          PERSONS_LIST: ${{ secrets.PERSONS_LIST }}
          EMAILS: ${{ secrets.EMAILS }}
          GMAIL_KEY: ${{ secrets.GMAIL_KEY }}
